### ISSUE TITLE
larger resolution?

### ISSUE THREAD

**Issue by iperov** [microsoft/FaceSynthetics#12]
can you please render in 1024 or 2048 res
512 is small enough for modern tasks

**Comment by bluesky314** [comment]
+1

**Comment by TadasBaltrusaitis** [comment]
Thanks for your interest in our FaceSynthetics dataset. This dataset is intended to accompany the ICCV paper submission and to help reproduce our results for face parsing and sparse landmark detection. The current release is as-is and we are not planning to include additional types of ground truth or images. Your suggestions are appreciated, and we will take them into consideration for any future dataset releases.
