### ISSUE TITLE
Dense Landmarks with 679 points  

### ISSUE THREAD

**Issue by hyperparameters** [microsoft/FaceSynthetics#14]
Please provide the dense landmarks as mentioned in the paper
679 points rather than just 70 points

**Comment by TadasBaltrusaitis** [comment]
Thanks for your interest in our FaceSynthetics dataset. This dataset is intended to accompany the ICCV paper submission and to help reproduce our results for face parsing and sparse landmark detection. The current release is as-is and we are not planning to include additional types of ground truth or images. Your suggestions are appreciated, and we will take them into consideration for any future dataset releases.
