### ISSUE TITLE
Code for generate the face

### ISSUE THREAD

**Issue by thuangb** [microsoft/FaceSynthetics#17]
Will you publish the code for synthesize the head model so that I can customize ?

**Comment by TadasBaltrusaitis** [comment]
Thanks for your interest in our FaceSynthetics dataset. This dataset is intended to accompany the ICCV paper submission and to help reproduce our results for face parsing and sparse landmark detection. The current release is as-is and we are not planning to include the image generation framework. Your suggestions are appreciated, and we will take them into consideration for any future dataset releases.
