### ISSUE TITLE
question about augmentation

### ISSUE THREAD

**Issue by QingpingZheng** [microsoft/FaceSynthetics#20]
Hi， I  want to know how do you do data augmentation？And do you train the network from scratch？

**Comment by TadasBaltrusaitis** [comment]
Yes, data augmentation is critical to train good models (please see Section 4.4 for details). For types of augmentation, also see Section 4.4, we include geometric augmentations (shifting, perspective, rotation, scaling) and appearance augmentations (shot noise, blur, greyscale, color shift, jpeg artifacts, contrast changes, gamma correction).

**Comment by TadasBaltrusaitis** [comment]
> And do you train the network from scratch？

Yes. We also tried using pre-trained models, but did not see much difference.
