### ISSUE TITLE
Can we get the blendshape values for the facial expressions?

### ISSUE THREAD

**Issue by hizzlehoff** [microsoft/FaceSynthetics#21]
The face in each image has an expression. Can we get the values for the blendshapes used to create these expressions for each image?

**Comment by florenttaralle** [comment]
Hi there, same question if gender and age are available :)

**Comment by friggog** [comment]
Hi - thanks for the interest in the dataset, unfortunately this release is intended to accompany the ICCV paper submission and we only have approval to release the data as it is here - we are not planning to include additional types of ground truth or images. We'll take your suggestions into consideration for any future dataset releases.

Regarding gender and age - the generated identities don't actually have a concept of gender or age. The texture comes from some identity with self-reported gender and age, but this does not correlate with the facial geometry or hair. What gender do we annotate for someone with female texture but geometry that many would interpret as masculine and a beard, for example? The same is somewhat true for age, though perhaps with other factors such as hair color playing a more active role.
