### ISSUE TITLE
Segmentation ground truth missing a label for mask on face(facewear)?

### ISSUE THREAD

**Issue by ggnaro** [microsoft/FaceSynthetics#22]
Hope that I did't got it wrong, but it seems to be that ground truth missing a label, for "facewear": 18.

I could got a heatmap image for facewear is labeled to be 0,  as same as background.
![image](https://user-images.githubusercontent.com/25218355/142366851-4df8e02e-a116-4ac0-926d-20a2cee53484.png)

So, it was intend to be, or due to some other reasons for that?
(Have read the paper, it said that "_we
dress our faces in headwear (36 items), facewear (7 items)
and eyewear (11 items) including helmets, head scarves, face
masks, and eyeglasses_")

**Comment by vvmatorin** [comment]
Any updates on this? Still an issue in the current dataset.

**Comment by iperov** [comment]
yes. This dataset is competely unusable shit.

**Comment by friggog** [comment]
Hey thanks for reporting this - it does look to be an error on our part in processing the segmentation GT - I’ok see if we are able to reprocess this

**Comment by iperov** [comment]
@friggog thank you very much. 

Then if you will reprocess it, can you please generate segmentation png separated for every label? 

Because for example I need skin label under mustache/beard, but in merged segmentation map this data is lost.

**Comment by iperov** [comment]
@friggog any news?

**Comment by iperov** [comment]
@friggog bro ?

**Comment by iperov** [comment]
@friggog mega shame

**Comment by TadasBaltrusaitis** [comment]
We are currently working on another dataset release (it is currently under review). The issue will be fixed in the future release.
