### ISSUE TITLE
Landmarks training example and results

### ISSUE THREAD

**Issue by nttstar** [microsoft/FaceSynthetics#23]
https://github.com/deepinsight/insightface/tree/master/alignment/synthetics

Just for reference.

**Comment by mdsanima** [comment]
That's cool!

**Comment by ForrestPi** [comment]
> https://github.com/deepinsight/insightface/tree/master/alignment/synthetics
> 
> Just for reference.

Could you provide the result of testing in real dataset?   I found that it dont work on face parsing task

**Comment by friggog** [comment]
Thanks for sharing this here - it's great to see the data used with success! As this isn't an issue as such I will close it, but hopefully people will find this link useful
