### ISSUE TITLE
Could you release corresponding synthetic 3d model?

### ISSUE THREAD

**Issue by John-Yao** [microsoft/FaceSynthetics#26]
Hi, Thanks for your great work!

I study in face systhetic and notice the great dataset. 

Could you release corresponding synthetic 3d model of  synthetic image? 

It may be brought more research topic on the dataset. Thanks!

**Comment by TadasBaltrusaitis** [comment]
Thanks for your interest in our FaceSynthetics dataset. This dataset is intended to accompany the ICCV paper submission and to help reproduce our results for face parsing and sparse landmark detection. The current release is as-is and we are not planning to include additional types of ground truth or images. Your suggestions are appreciated, and we will take them into consideration for any future dataset releases.
