### ISSUE TITLE
Is the hair library 3D models ?

### ISSUE THREAD

**Issue by xusensun** [microsoft/FaceSynthetics#29]
perfect project!

I want to know if is the hair library 3D models? 

looking forward your replying

**Comment by TadasBaltrusaitis** [comment]
They are indeed 3D objects (each hair strand is modeled individually as a curve). As per Section 3.4 of the paper:

> In contrast to other work which approximates hair with textures or coarse geometry, we represent hair as individual 3D strands, with a full head of hair comprising over 100,000 strands.
