### ISSUE TITLE
Is the process of attaching hair and eyebrows to head manual or automated?

### ISSUE THREAD

**Issue by X-niper** [microsoft/FaceSynthetics#30]
Thanks for this great work. I wonder the process of attaching hair and eyebrows to head manual or automated? If manually attaching, how long does it take?

Your responses are appreciated.

Regards

**Comment by TadasBaltrusaitis** [comment]
I would refer you to the section of the [paper](https://arxiv.org/pdf/2109.15102.pdf) on our hair library: 

> "512 scalp hair styles, 162 eyebrows, 142 beards, and 42 sets of eyelashes. Each asset was authored by a groom artist who specializes in creating digital hair. At render time, we randomly combine scalp, eyebrow, beard, and eyelash grooms.”

That is each of those assets was “manually” authored (i.e. created by a digital artist) and we attach those assets automatically to a sampled head at render time.
