### ISSUE TITLE
3D landmarks from a front view

### ISSUE THREAD

**Issue by chuanli11** [microsoft/FaceSynthetics#31]
Hi, Thanks for releasing the dataset.

It seems releasing 3D landmarks for the entire dataset is not part of the plan for near future. But I wonder if it is possible to share a reference set for the 70 3D landmarks from the front view, so the community can do pose estimation using methods such as Perspective-n-Point.

**Comment by friggog** [comment]
Hi - thanks for the interest in the dataset, unfortunately this release is intended to accompany the ICCV paper submission and we only have approval to release the data as it is here - we are not planning to include additional types of ground truth or images. We'll take your suggestions into consideration for any future dataset releases.
