### ISSUE TITLE
Multi view rendered images

### ISSUE THREAD

**Issue by eldercrow** [microsoft/FaceSynthetics#32]
First of all, thank you for this great work. I was wondering if the dataset could be expanded to provided images rendered from multiple camera directions, something similar to co3d from facebook. This will enable many additional research possibilities.

**Comment by TadasBaltrusaitis** [comment]
Thanks for your interest in our FaceSynthetics dataset. This dataset is intended to accompany the ICCV paper submission and to help reproduce our results for face parsing and sparse landmark detection. The current release is as-is and we are not planning to include additional types of ground truth or images. Your suggestions are appreciated, and we will take them into consideration for any future dataset releases.
