### ISSUE TITLE
Full annotations

### ISSUE THREAD

**Issue by r3krut** [microsoft/FaceSynthetics#34]
Hello! Thanks for the amazing work!
Do you plan to release of all types of annotations? I mean depth, normals, UVs, all points for head.
That would be cool!

**Comment by ashish-roopan** [comment]
+1

**Comment by friggog** [comment]
Hi - thanks for the interest in the dataset, unfortunately this release is intended to accompany the ICCV paper submission and we only have approval to release the data as it is here - we are not planning to include additional types of ground truth or images. We'll take your suggestions into consideration for any future dataset releases.

**Comment by iperov** [comment]
@friggog can you release at least right version of dataset? The dataset segmentation is wrong. For example Skin==background. Dataset is completely unusable now.
