### ISSUE TITLE
dense landmarks

### ISSUE THREAD

**Issue by htwdls** [microsoft/FaceSynthetics#37]
Hello! Thanks for the amazing work!
Do you plan to release of annotations about depth landmark?
That would be cool!

**Comment by ChrisTiger93** [comment]
Also interested in data for training dense landmarks

**Comment by ashish-roopan** [comment]
+1

**Comment by Tinkle78** [comment]
+1

**Comment by lyj96** [comment]
+1

**Comment by Victcode** [comment]
+1

**Comment by friggog** [comment]
Hi - thanks for the interest in the dataset, unfortunately this release is intended to accompany the ICCV paper submission and we only have approval to release the data as it is here - we are not planning to include additional types of ground truth or images. We'll take your suggestions into consideration for any future dataset releases.
