### ISSUE TITLE
Mirroring FaceSynthetics on Hugging Face

### ISSUE THREAD

**Issue by NimaBoscarino** [microsoft/FaceSynthetics#41]
Hello! Thank you for creating and publishing this dataset 😄 Would you be interested in uploading it to the [Hugging Face dataset hub](https://huggingface.co/datasets)? Hosting is free, and I know our users would find this dataset extremely valuable. Beyond helping with discoverability, datasets on Hugging Face can be used with the `datasets` library (https://github.com/huggingface/datasets), which enables things like streaming and also provides a ton of efficient data-manipulation tools.

We have [guides on how to upload datasets](https://huggingface.co/docs/hub/datasets-adding) if this is something you're interested in, but I'm also happy to help out with this myself!

cc: @osanseviero

**Comment by pcuenca** [comment]
@NimaBoscarino I uploaded the dataset to the hub: https://huggingface.co/datasets/pcuenq/face_synthetics.

Happy to move it to a Microsoft organization if necessary.
