### ISSUE TITLE
Alpha background masks.

### ISSUE THREAD

**Issue by GilesBathgate** [microsoft/FaceSynthetics#42]
If you could release the Alpha masks shown in the paper, they would be really useful for training background matting models (for example PaddlePaddleSeg PP-Matting)

The segmentation images only contain a binary background class, so applying these as masks can result in a halo effect.

**Comment by friggog** [comment]
Hi - thanks for the interest in the dataset, unfortunately this release is intended to accompany the ICCV paper submission and we only have approval to release the data as it is here - we are not planning to include additional types of ground truth or images. We'll take your suggestions into consideration for any future dataset releases.

**Comment by iperov** [comment]
this is suxx and useless dataset.
