### ISSUE TITLE
wrap3d manually or with python scripts?

### ISSUE THREAD

**Issue by X-niper** [microsoft/FaceSynthetics#43]
Hi, you have mentioned that you register your head models with r3ds. I want to know whether this process is automated or manual? Specifically, how you choose the corresponding keypoints, which consumes quite a lot of time.  After 'wraping', will you modify the wrapped results further to get better results?

**Comment by friggog** [comment]
The process was largely manual - choosing correspondence points and some manual fixup of the wrap results - and yes this did consume quite a lot of time 😅 The goals were to represent the original scan geometry as best as possible and keep the topology consistent across scans, ie the same polys should be representing the same semantic region of the face across all identities. It is possible to automate some of the correspondence finding using landmark detection DNNs for example, but the precision is often not be good enough to give very good wrap results, so still needs manual tuning. As this data is the basis of pretty much everything else in the pipeline the quality needs to be very high.
