### ISSUE TITLE
Will you release 703 landmarks dataset?

### ISSUE THREAD

**Issue by watermoon123** [microsoft/FaceSynthetics#44]
Will you release 703 landmarks dataset as used in <3D Face Reconstruction with Dense Landmarks>?
Thank you

**Comment by friggog** [comment]
Hi - thanks for the interest in the dataset, unfortunately this release is intended to accompany the ICCV paper submission and we only have approval to release the data as it is here - we are not planning to include additional types of ground truth or images. We'll take your suggestions into consideration for any future dataset releases.
