### ISSUE TITLE
dense landmarks?

### ISSUE THREAD

**Issue by yin-zhang** [microsoft/FaceSynthetics#47]
Hi!  Besides the 70 sparse landmarks, is it possible to get the ~700 dense landmarks ？

**Comment by TadasBaltrusaitis** [comment]
Hi - thanks for the interest in the dataset, unfortunately this release is intended to accompany the ICCV paper submission and we only have approval to release the data as it is here - we are not planning to include additional types of ground truth or images. We'll take your suggestions into consideration for any future dataset releases.
