### ISSUE TITLE
Could you provide color-PALETTE of the dataset? You know it is a must when training sometimes.

### ISSUE THREAD

**Issue by Beyondzjl** [microsoft/FaceSynthetics#48]

**Comment by iperov** [comment]
currently dataset is broken and unusable. 
I am already waiting the fix more than 2 months

**Comment by Beyondzjl** [comment]
Actually the dataset can be used well but there is not color-palette of it, maybe I need to redefine them. But you know it may leads to some confusion when the work be posted on different platforms.

**Comment by Beyondzjl** [comment]
All right bro, I have got what you mean. The GTs really are broken. It is so sad that the offical haven't correct them yet .

**Comment by TadasBaltrusaitis** [comment]
We rendered all the data in RAW format, so without using any colour palette or colour transform. This data was then converted using simple gamma correction (with value 2.2). Hope this helps

**Comment by iperov** [comment]
@TadasBaltrusaitis but the dataset is unusable , will you fix it?

**Comment by TadasBaltrusaitis** [comment]
We are currently working on another dataset release (it is currently under review). The issue will be fixed in the future release.
