### ISSUE TITLE
separate categories?

### ISSUE THREAD

**Issue by iperov** [microsoft/FaceSynthetics#7]
> {frame_id}_seg.png    # Segmentation image, where each pixel has an integer value mapping to the categories below

then how to get the SKIN label under GLASSES ?

![firefox_2021-10-11_19-57-16](https://user-images.githubusercontent.com/8076202/136820368-6af12289-e2b6-4d15-8ea5-f9bb312983a9.png)

can you please re-render whole dataset with separated categories?

**Comment by friggog** [comment]
Hi - thanks for the interest in the dataset, unfortunately this release is intended to accompany the ICCV paper submission and we only have approval to release the data as it is here - we are not planning to include additional types of ground truth or images. We'll take your suggestions into consideration for any future dataset releases.

**Comment by iperov** [comment]
just bury your useless repo
