### ISSUE TITLE
3D landmarks?

### ISSUE THREAD

**Issue by iperov** [microsoft/FaceSynthetics#8]
is it so difficult to provide 3d landmarks?

without 3D we cannot estimate pitch/yaw/roll correctly.

**Comment by TadasBaltrusaitis** [comment]
Thanks for your interest in our FaceSynthetics dataset. This dataset is intended to accompany the ICCV paper submission and to help reproduce our results for face parsing and sparse landmark detection. The current release is as-is and we are not planning to include additional types of ground truth or images. Your suggestions are appreciated, and we will take them into consideration for any future dataset releases.

**Comment by bluesky314** [comment]
Why are you guys not releasing the full set and models @TadasBaltrusaitis ?

**Comment by 07hyx06** [comment]
Hi, Thanks for your great work! Do you have a plan to release the corresponding attributes in Figure 12 (i.e. depth map, albedo, etc.) for each image in the dataset?

**Comment by bluesky314** [comment]
Why are you guys not releasing the full set and models @TadasBaltrusaitis ?
